/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[1];
new PlayerText:PlayerTD[MAX_PLAYERS][1];

//Textdraws
AchTextFetch = TextDrawCreate(245.000000, 111.000000, "~y~Fetching_Achievement_Data...");
TextDrawFont(AchTextFetch, 3);
TextDrawLetterSize(AchTextFetch, 0.295833, 1.700000);
TextDrawTextSize(AchTextFetch, 400.000000, 17.000000);
TextDrawSetOutline(AchTextFetch, 1);
TextDrawSetShadow(AchTextFetch, 0);
TextDrawAlignment(AchTextFetch, 1);
TextDrawColor(AchTextFetch, -1);
TextDrawBackgroundColor(AchTextFetch, 255);
TextDrawBoxColor(AchTextFetch, 50);
TextDrawUseBox(AchTextFetch, 0);
TextDrawSetProportional(AchTextFetch, 1);
TextDrawSetSelectable(AchTextFetch, 0);


//Player Textdraws
PlayerTD[ChallengeVehInfo][playerid] = CreatePlayerTextDraw(playerid, 3.000000, 281.000000, "~w~Vehicle_Nitro:_~g~Available~n~~w~Vehicle_Fix:_~g~Avaiable");
PlayerTextDrawFont(playerid, PlayerTD[ChallengeVehInfo][playerid], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[ChallengeVehInfo][playerid], 0.379166, 1.300000);
PlayerTextDrawTextSize(playerid, PlayerTD[ChallengeVehInfo][playerid], 160.000000, 14.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[ChallengeVehInfo][playerid], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[ChallengeVehInfo][playerid], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[ChallengeVehInfo][playerid], 1);
PlayerTextDrawColor(playerid, PlayerTD[ChallengeVehInfo][playerid], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[ChallengeVehInfo][playerid], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[ChallengeVehInfo][playerid], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[ChallengeVehInfo][playerid], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[ChallengeVehInfo][playerid], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[ChallengeVehInfo][playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
