/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[9];

//Textdraws
PublicTD[0] = TextDrawCreate(19.000000, 317.000000, "~y~~h~Freeroam_~b~~h~World");
TextDrawFont(PublicTD[0], 0);
TextDrawLetterSize(PublicTD[0], 0.412499, 1.899999);
TextDrawTextSize(PublicTD[0], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[0], 2);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 1);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 50);
TextDrawUseBox(PublicTD[0], 0);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(10.000000, 430.000000, "~y~Stunt~w~/~r~Minigames~w~/~g~Fun");
TextDrawFont(PublicTD[1], 2);
TextDrawLetterSize(PublicTD[1], 0.237498, 1.700000);
TextDrawTextSize(PublicTD[1], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 0);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(17.000000, 249.000000, "~y~Points~w~:~n~__~b~Score~w~:_100~n~__~r~Cash~w~:_$20,000,000");
TextDrawFont(PublicTD[2], 3);
TextDrawLetterSize(PublicTD[2], 0.304162, 1.499999);
TextDrawTextSize(PublicTD[2], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 1);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 50);
TextDrawUseBox(PublicTD[2], 0);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);

PublicTD[3] = TextDrawCreate(99.000000, 403.000000, "1300_KM/H");
TextDrawFont(PublicTD[3], 2);
TextDrawLetterSize(PublicTD[3], 0.283333, 1.950000);
TextDrawTextSize(PublicTD[3], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[3], 2);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 1);
TextDrawColor(PublicTD[3], 16777215);
TextDrawBackgroundColor(PublicTD[3], 255);
TextDrawBoxColor(PublicTD[3], 50);
TextDrawUseBox(PublicTD[3], 0);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 0);

PublicTD[4] = TextDrawCreate(274.000000, 415.000000, "~y~[~y~Oblivion_~w~gone_to_~p~/restanrant");
TextDrawFont(PublicTD[4], 2);
TextDrawLetterSize(PublicTD[4], 0.141662, 1.149996);
TextDrawTextSize(PublicTD[4], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[4], 1);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 1);
TextDrawColor(PublicTD[4], -1);
TextDrawBackgroundColor(PublicTD[4], 255);
TextDrawBoxColor(PublicTD[4], 50);
TextDrawUseBox(PublicTD[4], 0);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 0);

PublicTD[5] = TextDrawCreate(268.000000, 427.000000, "Use /v to spawn your vehicle");
TextDrawFont(PublicTD[5], 2);
TextDrawLetterSize(PublicTD[5], 0.162496, 1.500000);
TextDrawTextSize(PublicTD[5], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[5], 1);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 1);
TextDrawColor(PublicTD[5], 35839);
TextDrawBackgroundColor(PublicTD[5], 255);
TextDrawBoxColor(PublicTD[5], 50);
TextDrawUseBox(PublicTD[5], 0);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 0);

PublicTD[6] = TextDrawCreate(90.000000, 350.000000, "~w~Your_~y~GodMode_~w~has_been_~r~disabled");
TextDrawFont(PublicTD[6], 1);
TextDrawLetterSize(PublicTD[6], 0.174998, 1.250000);
TextDrawTextSize(PublicTD[6], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[6], 1);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 1);
TextDrawColor(PublicTD[6], -1);
TextDrawBackgroundColor(PublicTD[6], 255);
TextDrawBoxColor(PublicTD[6], 50);
TextDrawUseBox(PublicTD[6], 0);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 0);

PublicTD[7] = TextDrawCreate(542.000000, 80.000000, "~g~GODMODE");
TextDrawFont(PublicTD[7], 2);
TextDrawLetterSize(PublicTD[7], 0.416666, 1.799998);
TextDrawTextSize(PublicTD[7], 321.500000, 20.500000);
TextDrawSetOutline(PublicTD[7], 2);
TextDrawSetShadow(PublicTD[7], 3);
TextDrawAlignment(PublicTD[7], 1);
TextDrawColor(PublicTD[7], -1);
TextDrawBackgroundColor(PublicTD[7], 255);
TextDrawBoxColor(PublicTD[7], 99);
TextDrawUseBox(PublicTD[7], 0);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 0);

PublicTD[8] = TextDrawCreate(239.000000, 368.000000, "~y~Objects_Loading...");
TextDrawFont(PublicTD[8], 2);
TextDrawLetterSize(PublicTD[8], 0.391665, 2.000000);
TextDrawTextSize(PublicTD[8], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[8], 1);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 1);
TextDrawColor(PublicTD[8], -16776961);
TextDrawBackgroundColor(PublicTD[8], 255);
TextDrawBoxColor(PublicTD[8], 202);
TextDrawUseBox(PublicTD[8], 1);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
